### ISSUE TITLE
Error con el android Usuario PC SF205-19

### ISSUE THREAD

**Issue by ferchoba** [alejo8591/unipiloto-apm-4#10]
Este es el error que sale al ejecutar cordova emulate android

Waiting for emulator to start...
Error: Failed to execute shell command "getprop,dev.bootcomplete"" on device: Er
ror: C:\android\platform-tools\adb.exe: Command failed with exit code 4294967295
 Error output:
error: could not install _smartsocket_ listener: cannot bind to 127.0.0.1:5037:
Sólo se permite un uso de cada dirección de socket (protocolo/dirección de red/p
uerto) (10048)
*\* daemon still not running
could not read ok from ADB Server
- failed to start daemon *
  error: cannot connect to daemon

**Comment by jeqs** [comment]
Hace referencia al Issue #13 : "Este error se presenta cuando esta en ejecución dos AVD o dos administradores de dispositivos virtuales de Android. En este caso, me di cuenta que se estaba en ejecución el AVD Manager que trae el SDK de Androird y AVD de Genymotion. Al cerrar AVD de Genymotion completamente (incluso finalizando la tarea por el Administrador de Tareas de Windows) y trabajando solo con el AVD manager del SDK de Android, no vuelve aparecer el error. No es una solución definitiva pero se puede trabajar de esa manera."

**Comment by alejo8591** [comment]
https://github.com/alejo8591/unipiloto-apm-4/issues/13
