### ISSUE TITLE
Error en el computador SF205-20

### ISSUE THREAD

**Issue by dianamavega** [alejo8591/unipiloto-apm-4#11]
ANDROID_HOME=C:\android
JAVA_HOME=C:\Program Files\Java\jdk1.7.0_79
Error: C:\android\platform-tools\adb.exe: Command failed with exit code 1 Error
output:
error: could not install _smartsocket_ listener: cannot bind to 127.0.0.1:5037:
Sólo se permite un uso de cada dirección de socket (protocolo/dirección de red/p
uerto) (10048)
could not read ok from ADB Server
- failed to start daemon *
  error: cannot connect to daemon

**Comment by jeqs** [comment]
Hace referencia al Issue #13 : "Este error se presenta cuando esta en ejecución dos AVD o dos administradores de dispositivos virtuales de Android. En este caso, me di cuenta que se estaba en ejecución el AVD Manager que trae el SDK de Androird y AVD de Genymotion. Al cerrar AVD de Genymotion completamente (incluso finalizando la tarea por el Administrador de Tareas de Windows) y trabajando solo con el AVD manager del SDK de Android, no vuelve aparecer el error. No es una solución definitiva pero se puede trabajar de esa manera."

**Comment by alejo8591** [comment]
https://github.com/alejo8591/unipiloto-apm-4/issues/13
