### ISSUE TITLE
Problema al ejecutar aplicacion en Cordova

### ISSUE THREAD

**Issue by Divier** [alejo8591/unipiloto-apm-4#12]
Al ejecutar el comando:

cordova run android se genera el error de la imagen adjunta.
![captura error](https://cloud.githubusercontent.com/assets/20135150/17078263/c6b77336-50b3-11e6-81e9-374fc0b279a6.JPG)

**Comment by jeqs** [comment]
Hace referencia al Issue #13 : "Este error se presenta cuando esta en ejecución dos AVD o dos administradores de dispositivos virtuales de Android. En este caso, me di cuenta que se estaba en ejecución el AVD Manager que trae el SDK de Androird y AVD de Genymotion. Al cerrar AVD de Genymotion completamente (incluso finalizando la tarea por el Administrador de Tareas de Windows) y trabajando solo con el AVD manager del SDK de Android, no vuelve aparecer el error. No es una solución definitiva pero se puede trabajar de esa manera."

**Comment by alejo8591** [comment]
https://github.com/alejo8591/unipiloto-apm-4/issues/13
