### ISSUE TITLE
Error en SF205-09 Node.js - Cordova run android

### ISSUE THREAD

**Issue by jeqs** [alejo8591/unipiloto-apm-4#13]
Error: Failed to execute shell command "getprop,dev.bootcomplete"" on device: Error: C:\android\plat
form-tools\adb.exe: Command failed with exit code 1 Error output:
error: could not install _smartsocket_ listener: cannot bind to 127.0.0.1:5037: Sólo se permite un u
so de cada dirección de socket (protocolo/dirección de red/puerto) (10048)
could not read ok from ADB Server
- failed to start daemon *
  error: cannot connect to daemon
  ![error](https://cloud.githubusercontent.com/assets/1850589/17078526/6a8c28a6-50bb-11e6-958f-ff6c27454927.JPG)

**Comment by jeqs** [comment]
Este error se presenta cuando esta en ejecución dos AVD o dos administradores de dispositivos virtuales de Android. En este caso, me di cuenta que se estaba en ejecución el AVD Manager que trae el SDK de Androird y AVD de Genymotion. Al cerrar AVD de Genymotion completamente (incluso finalizando la tarea por el Administrador de Tareas de Windows) y trabajando solo con el AVD manager del SDK de Android, no vuelve aparecer el error. No es una solución definitiva pero se puede trabajar de esa manera.

**Comment by alejo8591** [comment]
![captura de pantalla 2016-07-26 a las 12 34 17 p m](https://cloud.githubusercontent.com/assets/1151850/17148631/8f826eda-532d-11e6-8191-4add9d5802ea.png)

![captura de pantalla 2016-07-26 a las 12 37 31 p m](https://cloud.githubusercontent.com/assets/1151850/17148792/22730b50-532e-11e6-94ee-88a4d1a98b1e.png)

**Comment by alejo8591** [comment]
Fix solved
