### ISSUE TITLE
Error en instalación wampserver

### ISSUE THREAD

**Issue by milepola** [alejo8591/unipiloto-apm-4#14]
Hola Alejandro buenos días, 

Tuve problemas con la instalación del wampserver y no me ejecuta, me podría indicar que puede ser? Adjunto la imagen del error que me salió. "El programa no puede iniciarse porque falta VCRUNTIME140.dll en el equipo" 
![error wampserver](https://cloud.githubusercontent.com/assets/20135614/17084702/66ef6cec-518a-11e6-9f0b-c528a15dcd7e.jpg)

**Comment by alejo8591** [comment]
@milepola debes verificar que estén descargado e instalados estos paquetes:
1. VC9 Packages (Visual C++ 2008 SP1)
   - http://www.microsoft.com/en-us/download/details.aspx?id=5582
   - http://www.microsoft.com/en-us/download/details.aspx?id=2092
2. VC10 Packages (Visual C++ 2010 SP1)
   - http://www.microsoft.com/en-us/download/details.aspx?id=8328
   - http://www.microsoft.com/en-us/download/details.aspx?id=13523
3. VC11 Packages (Visual C++ 2012 Update 4) Los dos archivos **`VSU4\vcredist_x86.exe`** and **`VSU4\vcredist_x64.exe`** descargar en: http://www.microsoft.com/en-us/download/details.aspx?id=30679
4. VC13 Packages (Visual C++ 2013) Los dos archivos **`VSU4\vcredist_x86.exe`** and **`VSU4\vcredist_x64.exe`** descargar en:  https://www.microsoft.com/en-us/download/details.aspx?id=40784
5. VC14 Packages (Visual C++ 2015) Los dos archivos **`vcredist_x86.exe`** and **`vcredist_x64.exe`** descargar en: http://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by alejo8591** [comment]
solved!!
