### ISSUE TITLE
Este es el link del repositorio 

### ISSUE THREAD

**Issue by alexospina7** [alejo8591/unipiloto-apm-4#15]
https://github.com/alexospina7/Lab_guia1 el problema es que no se minifican los archivos js ni html del ejercicio5, aunque el index.html ayer se minifico sin embargo cuando fui a minificar los archivos html de la carpeta views no me salio.

**Comment by alejo8591** [comment]
@alexospina7 por favor especificar el ejercicio con problemas, adicional más información de como estas haciendo el proceso

**Comment by alexospina7** [comment]
El ejercicio es el numero 5 , primero modifico el archivo gulpfile e incluyo los archivos los cuales voy a minificar, en segundo lugar utilizo en la linea de comandos los plugins gulp uglify --save-dev,  Seguido a esto, en la linea de comandos utilizo gulp uglify y me aparece el siguiente error" gulp is not defined".
Inicialmente pensaba que no había instalado gulp, sin embargo en la linea de comandos utilice npm install -g gulp, y empece de nuevo el proceso de minificar y no salio.

**Comment by alejo8591** [comment]
Esto es lo que [encuentro en el ejercicio](https://github.com/alexospina7/Lab_guia1/blob/master/ejercicio5/gulpfile.js)

``` javascript
gulp.task('uglify', function() {
  gulp.src(['app.js', 'controllers.js'])
    .pipe(uglify('app.js', {
      mangle: false,
      output: {
        beautify: true
      }
    }))
    .pipe(gulp.dest('dist1/js'))
});
```

Esta mal la estructura del archivo, [por favor revisa este enlace y rectifica tu ejercicio](https://github.com/alejo8591/unipiloto-apm-4/blob/master/modules/module_5/lab1/gulpfile.js).

**Comment by alexospina7** [comment]
listo ya me minifico y para archivos html cual es?

**Comment by alejo8591** [comment]
Con el plugin [gulp-htmlmin](https://www.npmjs.com/package/gulp-htmlmin/):
y el código de ejemplo según la documentación es:

``` javascript
var gulp = require('gulp');
var htmlmin = require('gulp-htmlmin');

gulp.task('minify', function() {
  return gulp.src('src/*.html')
    .pipe(htmlmin({collapseWhitespace: true}))
    .pipe(gulp.dest('dist'))
});
```

**Comment by alexospina7** [comment]
si, ya lo encontré
