### ISSUE TITLE
No permite borrar carpetas

### ISSUE THREAD

**Issue by milepola** [alejo8591/unipiloto-apm-4#16]
Hola Alejandro, 

Adjunto la imagen del mensaje que sale al borrar una carpeta de los ejercicios, no permite borrarla
![noborra](https://cloud.githubusercontent.com/assets/20135614/17387212/265288ba-59b7-11e6-9903-e3c1b3380816.jpg)

**Comment by jeqs** [comment]
Prueba llegando hasta esa carpeta que te sale el error y le cambias el nombre a uno corto Ej "a" y trate de eliminar la nuevamente.

**Comment by alejo8591** [comment]
@milepola y @jeqs por favor prueben con el siguiente paquete de [Node.JS llamado RimRaf](https://github.com/isaacs/rimraf) y las siguientes opciones:
- `npm install rimraf -g` instalar paquete `global`
- `rimraf node_modules` ejecutar comando para borrar

**Comment by jeqs** [comment]
Funciona correctamente.

Instale el gulp y creo la carpeta node_modules. Probé ejecutando el comando de rimraf node_modules y elimina toda la carpeta correctamente.

Tener cuidado al usar este comando. No muestra mensaje de validación o pregunta si quiere borrarlo. Lo elimina de una vez y tampoco lo pasa a la papelera de reciclaje. Elimina cualquier cosa, carpeta y archivos.extensión sin problemas.

Muchas gracias.
