### ISSUE TITLE
Error en ejecución wampserver

### ISSUE THREAD

**Issue by jeqs** [alejo8591/unipiloto-apm-4#17]
Buen día.

He instalado dos veces la versión 3.0.4 de Wampserver64bits y al tratar de iniciar los servicios me genera este error.

![errorwamp](https://cloud.githubusercontent.com/assets/1850589/17449974/6394dc60-5b23-11e6-89a6-43251a6031d3.JPG)

Al parecer uno de dos servicio no inicia.

Muchas gracias.

**Comment by alejo8591** [comment]
Por favor prueba con estas otras dos opciones de servidores Web: 
- [MAMP Server Inicialmente era para OS X](https://www.mamp.info/en/downloads/) pero ya tiene una versión muy estable para Windows.
- [XAMPP Server es otra opción](https://www.apachefriends.org/es/download.html) muy buena y estable.

**Comment by jeqs** [comment]
Instale XAMPP sobre un Windows 8.1 64bits y funciona bien. 

Muchas gracias
