### ISSUE TITLE
Duda sobre paquete de Instalación Android SDK

### ISSUE THREAD

**Issue by jeqs** [alejo8591/unipiloto-apm-4#18]
Buen día

Actualmente solo quiero instalar el Android SDK Manager, pero al tratar de bajarlo e instalarlo me dice que debo instalar Android Studio desde el sitio https://developer.android.com/, alguien tiene una URL donde pueda bajar solo el Android SDK sin tener que instalar en Android Studio?

Gracias

**Comment by alejo8591** [comment]
Sí es posible descargarlo, en la sección llamada `Get just the command line tools` de la [sección Android Studio de Android Developers](https://developer.android.com/studio/index.html) al final de la pagina:

![captura de pantalla 2016-08-09 a las 5 32 21 p m](https://cloud.githubusercontent.com/assets/1151850/17536048/fdddb990-5e57-11e6-9d21-259fc6d2fbec.png)

**Comment by jeqs** [comment]
Funca, muchas gracias.
