### ISSUE TITLE
MEAN Stack Tutorial gratis en Udemy

### ISSUE THREAD

**Issue by crishood** [alejo8591/unipiloto-apm-4#19]
[http://on.codek.tv/VJFKOtRWW](url)

**Comment by jeqs** [comment]
Hola @crishood 

El link no funciona si le doy click. Si lo copio y pego en el explorador si funciona. 

Esta es la URL del curso [https://www.udemy.com/master-the-mean-stack/](url)

Muchas gracias por el aporte.
