### ISSUE TITLE
error al compilar el proyecto ionic en plataforma android

### ISSUE THREAD

**Issue by alexospina7** [alejo8591/unipiloto-apm-4#22]
![imagen_repositorio](https://cloud.githubusercontent.com/assets/20135113/17608089/a89b458a-5fef-11e6-929d-a0403e41c36c.jpg)

**Comment by alejo8591** [comment]
## Advertencia: Tener mucho cuidado con las variables de entorno pues pueden dañar el sistema operativo

> Por favor tener en cuenta lo resaltado en amarillo para cada imagen

### Abrir las propiedades del equipo y buscar la opción `Configuración avanzada del sistema`

![cap1](https://cloud.githubusercontent.com/assets/1151850/17639918/30584a90-60bd-11e6-9ffa-2b56bcafcc60.PNG)

### Luego la opción de variables de entorno

![cap2](https://cloud.githubusercontent.com/assets/1151850/17639936/69bd5f3c-60bd-11e6-8b0e-8e526442228d.PNG)

### Buscar y/o crear la variable `ANDROID_HOME` con la ruta especifica en donde esta guardado el `SDK Manager` que se descargo anteriormente:

![cap3](https://cloud.githubusercontent.com/assets/1151850/17639958/d28e908a-60bd-11e6-857a-c8140e2a12ae.PNG)

### Luego se agrega a la variable global, llamada `Path` del sistema pera como variable `%ANDROID_HOME%`

![cap4](https://cloud.githubusercontent.com/assets/1151850/17639978/11855814-60be-11e6-891d-9aed013b42ea.PNG)

> En algunos casos hay que reiniciar el computador.

**Comment by alexospina7** [comment]
![imagen1](https://cloud.githubusercontent.com/assets/20135113/17706200/babb80e0-63a0-11e6-8f5f-6921e5e87dd8.jpg)

**Comment by alexospina7** [comment]
![imagen2](https://cloud.githubusercontent.com/assets/20135113/17706213/c733c88c-63a0-11e6-92a5-cb66e1548fb2.jpg)

**Comment by alexospina7** [comment]
![imagen3](https://cloud.githubusercontent.com/assets/20135113/17706231/d3fe17e8-63a0-11e6-8545-d9781710ba29.jpg)

**Comment by alexospina7** [comment]
Se crea el android home
![imagen4](https://cloud.githubusercontent.com/assets/20135113/17706244/defb5caa-63a0-11e6-82fc-bf6e5615905b.jpg)

**Comment by alexospina7** [comment]
![imagen5](https://cloud.githubusercontent.com/assets/20135113/17706256/ece05d48-63a0-11e6-8ccd-0f0b9e20c65f.jpg)

**Comment by alexospina7** [comment]
![imagen6](https://cloud.githubusercontent.com/assets/20135113/17706261/f6a977b0-63a0-11e6-9a23-f5b481d17127.jpg)

**Comment by alejo8591** [comment]
@alexospina7 procura enviar en un solo post las imagenes, me satura el correo con tantas publicaciones

**Comment by alexospina7** [comment]
ok

**Comment by alejo8591** [comment]
@alexospina7 donde esta la `JAVA_HOME` donde instala el JDK?

**Comment by alexospina7** [comment]
yo instale el jdk 8u102 pero no lo encuentro

**Comment by alejo8591** [comment]
@alexospina7 revisa en `Archivos de Progama` la carpeta llamada `java` y dentro de ella debe haber una que antecede la palabra `JDK`

**Comment by alexospina7** [comment]
listo ya la encontré

**Comment by alexospina7** [comment]
que hago ahora?

**Comment by alejo8591** [comment]
1. Establecer la variable de entorno `JAVA_HOME` en la ubicación de la instalación del JDK
2. Establecer la variable de entorno `ANDROID_HOME` a la ubicación de la instalación del `SDK Android`
3. También agregar las herramientas del `SDK Android`: `platform-tools` y `tools`

**Comment by alexospina7** [comment]
no entiendo muy bien JAVA_HOME , es necesario crearlo y colocar la dirección del JDK?
