### ISSUE TITLE
No puedo abrir un archivo angularJS

### ISSUE THREAD

**Issue by alexospina7** [alejo8591/unipiloto-apm-4#30]
![ayudaangular](https://cloud.githubusercontent.com/assets/20135113/22161731/afd5bfde-df19-11e6-8106-f1f5ef21eb9f.jpg)
![ayudaangular2](https://cloud.githubusercontent.com/assets/20135113/22161752/ba2069c6-df19-11e6-9c5d-00e16534cb61.jpg)

tengo instalado wamp y tengo local server encendido también copié el proyecto dentro de la carpeta wamp64 en el www , sin embargo no me dejar ver el archivo angular,

**Comment by alejo8591** [comment]
@alexospina7 cómo se están invocando en los scripts de php, por favor indicar, que servidor estas usando?

**Comment by alexospina7** [comment]
estoy utilizando wamp

**Comment by alejo8591** [comment]
@alexospina7 entendido, pero como te dije por teléfono entre más información me des mejor te puedo ayudar... cómo se están invocando en los scripts de php o cómo los estes invocando?, sí me puedes mostrar parte del código para entender que estas haciendo...

**Comment by alexospina7** [comment]
no entiendo lo de los script de php muy bien, el ejercicio esta es modules/modules_3/lab18

**Comment by alejo8591** [comment]
que hay dentro de la carpeta `lab18` por favor dejame ver..!!

**Comment by alexospina7** [comment]
en la segunda imagen esta lo que hay dentro de la carpeta lab18

**Comment by alejo8591** [comment]
@alexospina7 seguro?

**Comment by alexospina7** [comment]
si

**Comment by alejo8591** [comment]
Pues le cuento que mi ojos me fallan porque yo no veo esto: 

![captura de pantalla 2017-01-20 a las 10 02 41 p m](https://cloud.githubusercontent.com/assets/1151850/22171444/30529424-df5c-11e6-9695-bb3b97cfe54d.png)

Lo que veo como segunda imagen es esto, y sí no estoy mal no veo nada parecido a la estructura de arriba:
![ba2069c6-df19-11e6-9c5d-00e16534cb61](https://cloud.githubusercontent.com/assets/1151850/22171454/5a746ef8-df5c-11e6-8ebd-6a37e0b5b91a.jpg)

**Comment by alexospina7** [comment]
si dentro de la carpeta lab18 esta exactamente lo que esta en el repositorio

**Comment by alejo8591** [comment]
perfecto por favor dejame ver, y ver la consola de JS

**Comment by alexospina7** [comment]
cual es la consola?

**Comment by alejo8591** [comment]
Por favor recordar lo visto como herramientas de debug... 

![captura de pantalla 2017-01-20 a las 10 19 47 p m](https://cloud.githubusercontent.com/assets/1151850/22171557/a0f2c7c4-df5e-11e6-856b-1a299adbc98b.png)

**Comment by alexospina7** [comment]
no aparece nada en la consola esta limpia

**Comment by alejo8591** [comment]
por favor desinstalar WAMP si es posible y luego instalar [XAMPP](https://www.apachefriends.org/es/download.html) o [MAMP](https://www.mamp.info/en/downloads/) después por favor probar...!!!

**Comment by alexospina7** [comment]
yo nunca he usado el xampp , y ya lo tengo instalado, me podrias explicar como usarlo?

**Comment by alejo8591** [comment]
[En este articulo mejor no puede estar explicado!!!](https://blog.udemy.com/tutorial-de-xampp-como-usar-xampp-para-ejecutar-su-propio-servidor-web/)

**Comment by alexospina7** [comment]
me sale el mismo error que con wamp

**Comment by alejo8591** [comment]
Pero luego te comiste esa guía en 5 minutos?, y de nuevo entre más información mejor, por favor imagen, imagen de la consola, pero necesito evidencias para poder ayudar

**Comment by alexospina7** [comment]
![ayudaangular3](https://cloud.githubusercontent.com/assets/20135113/22171714/093cac34-df62-11e6-9b7f-339c0d386415.jpg)

**Comment by alejo8591** [comment]
@alexospina7 necesito ver el contenido de la carpeta `lab18` sin eso no puedo ayudarte

**Comment by alejo8591** [comment]
ademas ese error al parecer esta activo un servidor IIS ese error no es de XAMPP

**Comment by alejo8591** [comment]
por favor matar todos los servidores demás que esten activos, pues si el error fuese de XAMPP, saldría algo así :
![y7ccq](https://cloud.githubusercontent.com/assets/1151850/22171748/fe917200-df62-11e6-9de6-e1919ceab832.png)

**Comment by alexospina7** [comment]
![ayudaangular4](https://cloud.githubusercontent.com/assets/20135113/22171755/33f5dbde-df63-11e6-9b92-7fdac3f6e62e.jpg)

**Comment by alejo8591** [comment]
Claro, no deja arrancar los servicios porque hay otro que los esta usando...!!! vez que si puedes enviar imagenes :/

![093cac34-df62-11e6-9b7f-339c0d386415](https://cloud.githubusercontent.com/assets/1151850/22171762/4fe374e6-df63-11e6-8426-618fa4842453.jpg)

**Comment by alejo8591** [comment]
otra prueba de que ese error no es de WAMP, XAMPP o MAMP: http://stackoverflow.com/questions/5677099/routing-http-error-404-0-0x80070002

**Comment by alexospina7** [comment]
yo desactive el wamp

**Comment by alejo8591** [comment]
@alexospina7 si no me muestras imagenes o detalles del error con las palabras me queda difícil hacer debug de código, si se deja ayudar y sigue indicaciones lo solucionamos. Ese es error es de IIS

**Comment by alejo8591** [comment]
busque como era el error 404 de IIS y me sale tal cual lo que te sale, por favor apaga todos los servidores que tengas con IIS y ahí si prendes WAMP o XAMPP, si no te darán días tratando de ver que funcione. Por favor seguir instrucciones:

![captura de pantalla 2017-01-20 a las 10 58 33 p m](https://cloud.githubusercontent.com/assets/1151850/22171786/fe414bf8-df63-11e6-9e19-182acb18c82e.png)

**Comment by alexospina7** [comment]
como apago los servidores que tengo con IIS

**Comment by alejo8591** [comment]
No conozco mucho del tema IIS pero creo que esto te sirve: 

* [Primera Opción para hacerlo](https://technet.microsoft.com/es-es/library/jj635851(v=ws.11).aspx)
* [Segunda Opción para hacerlo](https://technet.microsoft.com/en-us/library/b9339773-7eff-4313-a14b-00f2b9f94ead)
* [Tercera Opción para hacerlo por si es win 10](http://stackoverflow.com/questions/30901434/iis-manager-in-windows-10)

**Comment by alexospina7** [comment]
![ayudaangular5](https://cloud.githubusercontent.com/assets/20135113/22171880/825101ac-df66-11e6-844f-f6df7cf6d9b5.jpg)

**Comment by alejo8591** [comment]
@alexospina7 estructura de la carpeta por favor

**Comment by alexospina7** [comment]
![ayudaangular6](https://cloud.githubusercontent.com/assets/20135113/22172342/e6c756b2-df71-11e6-86c9-c1b5adf5508d.jpg)

**Comment by alexospina7** [comment]
![ayudaangular7](https://cloud.githubusercontent.com/assets/20135113/22172378/e9703a18-df72-11e6-8409-0b8d17f1e48b.jpg)

**Comment by alexospina7** [comment]
se me cayo el internet anoche sorry

**Comment by alejo8591** [comment]
que versión de xampp tienes instalado y que por favor déjame ver el `XAMPP Control Panel` y ver como se encuentran los servicios.

**Comment by alexospina7** [comment]
![ayudaangular8](https://cloud.githubusercontent.com/assets/20135113/22176823/41bef688-dfe0-11e6-9aae-06f63ff3dd26.jpg)

**Comment by alejo8591** [comment]
están todos los servicios abajo, por favor reiniciar la maquina; verificar que no esten servicios de IIS arriba, luego si abrir y volver a ejecutar XAMPP hasta que los servicios pasen a verde como el MySQL. Y verificar que el WAMP también este apagado. Cuando hagas todos estos pasos por favor volver a enviar imagen de XAMPP Control Panel y de los servicios activos en el administrador de tareas de windows.

**Comment by alexospina7** [comment]
![ayudaangular9](https://cloud.githubusercontent.com/assets/20135113/22177029/2fb184fc-dfe4-11e6-93e9-6dfd99acbec3.jpg)
![ayudaangular10](https://cloud.githubusercontent.com/assets/20135113/22177030/3460bb1c-dfe4-11e6-9210-53afca6aafdd.jpg)

**Comment by alejo8591** [comment]
@alexospina7 pero falto el administrador de tareas de windows. Adicionalmente revisar si el WAMP tiene servicios arriba.

**Comment by alexospina7** [comment]
![ayudaangular11](https://cloud.githubusercontent.com/assets/20135113/22177388/82bfdc6a-dfea-11e6-9b10-f6509d31390b.jpg)

**Comment by alexospina7** [comment]
no tengo wamp arriba

**Comment by alexospina7** [comment]
![ayudaangular12](https://cloud.githubusercontent.com/assets/20135113/22177474/51953b4c-dfec-11e6-88e5-db96980a41a6.jpg)

cuando le doy click en xamp_start me aparece eso

**Comment by alejo8591** [comment]
Ese servicios `IIS Manager` para que sirve?, si lo bajas y vuelves intentar correr apache. Otra cosa en el XAMPP esta la opción de ver el log de eventos de Apache, por favor revisar y mostrarmelo.

**Comment by alexospina7** [comment]
IIS Manager supuestamente baja el IIS
![ayudaangular13](https://cloud.githubusercontent.com/assets/20135113/22177681/d2401092-dff0-11e6-8bdf-d54fa99a2848.jpg)

**Comment by alejo8591** [comment]
@alexospina7 de nuevo seguir instrucciones, entonces baje ese `IIS Manager`, segundo verifique en el botón de logs de Apache, porque el problema que tienes es que esta en conflicto el Apache y el servidor que esta arriba obviamente no tiene esos archivos:

![d2401092-dff0-11e6-8bdf-d54fa99a2848](https://cloud.githubusercontent.com/assets/1151850/22177695/5e20c71e-dff1-11e6-9d2b-facbfd077e8b.jpg)

**Comment by alexospina7** [comment]
Installing Apache HTTP Server 2.x with
 DomainName    = example.com
 ServerName    = www.example.com
 ServerAdmin   = admin@example.com
 ServerPort    = 80
 ServerSslPort = 443
 ServerRoot    = c:/Apache24
Rewrote docs/conf/extra/httpd-autoindex.conf.in
 to c:/Apache24/conf/original/extra/httpd-autoindex.conf
Rewrote docs/conf/extra/httpd-default.conf.in
 to c:/Apache24/conf/original/extra/httpd-default.conf
Rewrote docs/conf/extra/httpd-ssl.conf.in
 to c:/Apache24/conf/original/extra/httpd-ssl.conf
Rewrote docs/conf/extra/httpd-multilang-errordoc.conf.in
 to c:/Apache24/conf/original/extra/httpd-multilang-errordoc.conf
Rewrote docs/conf/extra/httpd-info.conf.in
 to c:/Apache24/conf/original/extra/httpd-info.conf
Rewrote docs/conf/extra/httpd-userdir.conf.in
 to c:/Apache24/conf/original/extra/httpd-userdir.conf
Rewrote docs/conf/extra/httpd-mpm.conf.in
 to c:/Apache24/conf/original/extra/httpd-mpm.conf
Rewrote docs/conf/httpd.conf.in
 to c:/Apache24/conf/original/httpd.conf
Rewrote docs/conf/extra/proxy-html.conf.in
 to c:/Apache24/conf/original/extra/proxy-html.conf
Rewrote docs/conf/extra/httpd-vhosts.conf.in
 to c:/Apache24/conf/original/extra/httpd-vhosts.conf
Rewrote docs/conf/extra/httpd-dav.conf.in
 to c:/Apache24/conf/original/extra/httpd-dav.conf
Rewrote docs/conf/extra/httpd-languages.conf.in
 to c:/Apache24/conf/original/extra/httpd-languages.conf
Rewrote docs/conf/extra/httpd-manual.conf.in
 to c:/Apache24/conf/original/extra/httpd-manual.conf
Duplicated c:/Apache24/conf/original/extra/httpd-autoindex.conf
 to c:/Apache24/conf/extra/httpd-autoindex.conf
Duplicated c:/Apache24/conf/original/extra/httpd-default.conf
 to c:/Apache24/conf/extra/httpd-default.conf
Duplicated c:/Apache24/conf/original/extra/httpd-ssl.conf
 to c:/Apache24/conf/extra/httpd-ssl.conf
Duplicated c:/Apache24/conf/original/extra/httpd-multilang-errordoc.conf
 to c:/Apache24/conf/extra/httpd-multilang-errordoc.conf
Duplicated c:/Apache24/conf/original/extra/httpd-info.conf
 to c:/Apache24/conf/extra/httpd-info.conf
Duplicated c:/Apache24/conf/original/extra/httpd-userdir.conf
 to c:/Apache24/conf/extra/httpd-userdir.conf
Duplicated c:/Apache24/conf/original/extra/httpd-mpm.conf
 to c:/Apache24/conf/extra/httpd-mpm.conf
Duplicated c:/Apache24/conf/original/httpd.conf
 to c:/Apache24/conf/httpd.conf
Duplicated c:/Apache24/conf/original/magic
 to c:/Apache24/conf/magic
Duplicated c:/Apache24/conf/original/charset.conv
 to c:/Apache24/conf/charset.conv
Duplicated c:/Apache24/conf/original/extra/proxy-html.conf
 to c:/Apache24/conf/extra/proxy-html.conf
Duplicated c:/Apache24/conf/original/extra/httpd-vhosts.conf
 to c:/Apache24/conf/extra/httpd-vhosts.conf
Duplicated c:/Apache24/conf/original/extra/httpd-dav.conf
 to c:/Apache24/conf/extra/httpd-dav.conf
Duplicated c:/Apache24/conf/original/mime.types
 to c:/Apache24/conf/mime.types
Duplicated c:/Apache24/conf/original/extra/httpd-languages.conf
 to c:/Apache24/conf/extra/httpd-languages.conf
Duplicated c:/Apache24/conf/original/extra/httpd-manual.conf
 to c:/Apache24/conf/extra/httpd-manual.conf

**Comment by alejo8591** [comment]
Este error quiere decir que hay conflictos con algún otro servidor:
```shell
Duplicated c:/Apache24/conf/original/extra/httpd-languages.conf
to c:/Apache24/conf/extra/httpd-languages.conf
Duplicated c:/Apache24/conf/original/extra/httpd-manual.conf
to c:/Apache24/conf/extra/httpd-manual.conf
```

**Solución para poder continuar ayudando: desinstalar XAMPP, WAMP y si es posible el IIS, reiniciar, volver a instalar XAMPP y probar.**

**Comment by alexospina7** [comment]
ya lo hice y sale el mismo error

**Comment by alejo8591** [comment]
@alexospina7 imagenes y detalle del proceso que hiciste, paso a paso..!!

**Comment by alejo8591** [comment]
Mira otros artículos que de seguro son de ayuda:

* [Solve IIS and XAMPP / WAMP conflict without changing ports](http://www.wrapcode.com/solve-iis-and-xampp-wampp-conflict-without-changing-ports/)
* [Using XAMPP and IIS together – Easy Solution](https://one7.wordpress.com/2009/04/28/using-xampp-and-iis-together-easy-solution/)
* [Problemas para que funcionen XAMP y IIS juntos](http://www.microteching.com/servidores/problemas-para-que-funcionen-xamp-y-iis-juntos-2)

**Comment by alexospina7** [comment]
![ayudaangular14](https://cloud.githubusercontent.com/assets/20135113/22178132/ee7993a8-dffc-11e6-9a61-da453b47b151.jpg)
![ayudaangular15](https://cloud.githubusercontent.com/assets/20135113/22178135/f606d40a-dffc-11e6-9126-5e084dfd784f.jpg)
![ayudaangular16](https://cloud.githubusercontent.com/assets/20135113/22178137/04f62d9e-dffd-11e6-87b6-9701892e61a3.jpg)
![ayudaangular17](https://cloud.githubusercontent.com/assets/20135113/22178139/0c4f58ae-dffd-11e6-8192-37ca4c92b4ec.jpg)
![ayudaangular18](https://cloud.githubusercontent.com/assets/20135113/22178138/0c4e9afe-dffd-11e6-8dd8-22a7d349b7f3.jpg)
![ayudaangular19](https://cloud.githubusercontent.com/assets/20135113/22178187/ef493684-dffd-11e6-8784-dfb387d29e59.jpg)
![ayudaangular20](https://cloud.githubusercontent.com/assets/20135113/22178188/ef492b3a-dffd-11e6-8731-a5d7e2189250.jpg)
![ayudaangular21](https://cloud.githubusercontent.com/assets/20135113/22178218/cff575da-dffe-11e6-8d25-e8e010c0f85e.jpg)
![ayudaangular22](https://cloud.githubusercontent.com/assets/20135113/22178216/cff47446-dffe-11e6-9c0d-b45a695fa5c3.jpg)
![ayudaangular23](https://cloud.githubusercontent.com/assets/20135113/22178217/cff47aae-dffe-11e6-8e1d-4f8015625f37.jpg)
![ayudaangular24](https://cloud.githubusercontent.com/assets/20135113/22178248/80fee352-dfff-11e6-9647-d87051b933d1.jpg)
![ayudaangular25](https://cloud.githubusercontent.com/assets/20135113/22178281/eedaf3ca-dfff-11e6-8b0a-20dfec1d1843.jpg)
![ayudaangular26](https://cloud.githubusercontent.com/assets/20135113/22178282/eedb77be-dfff-11e6-95b5-9bd4cc497c5c.jpg)

**Comment by alejo8591** [comment]
[Entonces seguir los últimos pasos indicados](https://github.com/alejo8591/unipiloto-apm-4/issues/30#issuecomment-274292048) y obviamente no tener WAMP instalado.

**Comment by alexospina7** [comment]
![ayudaangular27](https://cloud.githubusercontent.com/assets/20135113/22178595/e55c4e1c-e008-11e6-801e-e24b87597575.jpg)
la documentación: "Using XAMPP and IIS together – Easy Solution" fue de ayuda  ahora ya puedo utilizar el servidor xampp pero archivo angular no cambio sale como si lo ejecutara desde cualquier carpeta sin usar xampp

**Comment by alexospina7** [comment]
![ayudaangular27](https://cloud.githubusercontent.com/assets/20135113/22178616/b6807af4-e009-11e6-93f7-fe35340d5883.jpg)

la documentación: "Using XAMPP and IIS together – Easy Solution" fue de ayuda ahora ya puedo utilizar el servidor xampp pero archivo angular no cambio sale como si lo ejecutara desde cualquier carpeta sin usar xampp

**Comment by alejo8591** [comment]
@alexospina7 por favor mostrarme las herramientas de desarrollador

**Comment by alexospina7** [comment]
¿cuales son las herramientas de desarrollador? que pena no se!

**Comment by alejo8591** [comment]
👎 

* [Las herramientas de desarrollador del navegador, Chrome DevTools](https://github.com/alejo8591/unipiloto-apm-4/issues/30#issuecomment-274230195)

* [Documentación oficial de `Chrome DevTools`](https://developer.chrome.com/devtools)

**Comment by alexospina7** [comment]
![ayudaangular28](https://cloud.githubusercontent.com/assets/20135113/22178663/845fe33c-e00b-11e6-8b5a-60ef3c10f68b.jpg)

**Comment by alejo8591** [comment]
@alexospina7 Doy cierre al issues; porque eso es un error de angularJS, ya te toca verificar la estructura del ejercicio. El problema de este hilo es porque no te abrían los archivos y ya fue resuelto, por favor repasa lo visto, tiene que ver con los módulos y como se instancia en el ejercicio con respecto al `index.html`.

**Comment by alexospina7** [comment]
una cosita antes yo utilice el ejercicio que tienes en el repositorio C:\Users\usuario\Documents\Lab_apm4\unipiloto-apm-4-master\modules\module_3\lab18, entonces me parece muy raro que no sirva

**Comment by alexospina7** [comment]
una cosita antes yo utilice el ejercicio que tienes en el repositorio unipiloto-apm-4-master\modules\module_3\lab18, entonces me parece muy raro que no sirva
