### ISSUE TITLE
Porque no puedo ejecutar el ejercicio unipiloto-apm-4-master\modules\module_3\lab18

### ISSUE THREAD

**Issue by alexospina7** [alejo8591/unipiloto-apm-4#31]
![ayudaangular29](https://cloud.githubusercontent.com/assets/20135113/22267271/342d2e9a-e251-11e6-92b0-d92ca2fd9826.jpg)
![ayudaangular30](https://cloud.githubusercontent.com/assets/20135113/22267814/2e77a7bc-e253-11e6-9894-b75ea642a5b0.jpg)
![ayudaangular31](https://cloud.githubusercontent.com/assets/20135113/22267813/2e760344-e253-11e6-98a5-3075fc6e0db1.jpg)
![ayudaangular32](https://cloud.githubusercontent.com/assets/20135113/22267816/2e796552-e253-11e6-9fec-828e54919be8.jpg)
![ayudaangular33](https://cloud.githubusercontent.com/assets/20135113/22267815/2e78719c-e253-11e6-88df-91bb362c34ef.jpg)
![ayudaangular34](https://cloud.githubusercontent.com/assets/20135113/22267818/2e7cfe88-e253-11e6-81e6-72577cd5df1b.jpg)
![ayudaangular35](https://cloud.githubusercontent.com/assets/20135113/22267817/2e7a8478-e253-11e6-949e-bca4f8c311a0.jpg)
![ayudaangular36](https://cloud.githubusercontent.com/assets/20135113/22267820/2e8e8da6-e253-11e6-83a3-927b1b60cc80.jpg)
![ayudaangular37](https://cloud.githubusercontent.com/assets/20135113/22267819/2e8a00e2-e253-11e6-80a6-d5493e879517.jpg)

**Comment by alexospina7** [comment]
![ayudaangular28](https://cloud.githubusercontent.com/assets/20135113/22267851/4a5db37c-e253-11e6-8a0b-7861569bb537.jpg)

**Comment by alejo8591** [comment]
Cuál es el contenido de la carpeta completa, por favor con imagenes...

**Comment by alexospina7** [comment]
![ayudaangular38](https://cloud.githubusercontent.com/assets/20135113/22272441/07864af4-e268-11e6-9d69-af41efec94bf.jpg)
![ayudaangular39](https://cloud.githubusercontent.com/assets/20135113/22272442/0786c7d6-e268-11e6-93fc-a888b5c16c00.jpg)
![ayudaangular40](https://cloud.githubusercontent.com/assets/20135113/22272443/078b8546-e268-11e6-8d55-ef2590d866c3.jpg)
![ayudaangular41](https://cloud.githubusercontent.com/assets/20135113/22272451/13b84872-e268-11e6-9917-9c7f0f79c752.jpg)

**Comment by alejo8591** [comment]
el `ng-app="initial_spi"`en la etiqueta `<body>`

**Comment by alexospina7** [comment]
![ayudaangular42](https://cloud.githubusercontent.com/assets/20135113/22273340/2ea1bb54-e26e-11e6-8374-990a0d66ebd2.jpg)
![ayudaangular43](https://cloud.githubusercontent.com/assets/20135113/22273342/37534b82-e26e-11e6-9395-85ac83652a7f.jpg)

**Comment by alejo8591** [comment]
@alexospina7 el link que te da por favor copiarlo para ver el error....

![captura de pantalla 2017-01-24 a las 7 58 55 p m](https://cloud.githubusercontent.com/assets/1151850/22273604/aa6e6e0c-e26f-11e6-8b67-6af0e48b1f66.png)

**Comment by alexospina7** [comment]
http://errors.angularjs.org/1.5.7/$injector/modulerr?p0=initial_spi&p1=Erro…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.7%2Fangular.min.js%3A43%3A246

**Comment by alejo8591** [comment]
cambia el orden de carga de los scripts, poner de primeras los controladores y luego el app

**Comment by alexospina7** [comment]
no entiendo muy bien eso osea index lo pongo en una carpeta?

**Comment by alejo8591** [comment]
¿olvida lo anterior, en donde se esta exportando el `ngRoute`?, debes importar el módulo `ngRoute`:

```javascript
angular.module("initial_spi", ["ngRoute"])
.config(function($routeProvider) {
    $routeProvider
    .when("/", {
        templateUrl : "main.htm"
    })
    .when("/red", {
        templateUrl : "red.htm"
    })
    .when("/green", {
        templateUrl : "green.htm"
    })
    .when("/blue", {
        templateUrl : "blue.htm"
    });
});
```

Y no olvides dejar el `controllers.spi`

**Comment by alexospina7** [comment]
![ayudaangular31](https://cloud.githubusercontent.com/assets/20135113/22275052/f1439ab6-e277-11e6-8f34-3008991d84c9.jpg)

**Comment by alejo8591** [comment]
falta agregar el `ngRoute`

**Comment by alexospina7** [comment]
![ayudaangular44](https://cloud.githubusercontent.com/assets/20135113/22275368/4749bbb4-e27a-11e6-8dd3-417f71472d19.jpg)
![ayudaangular45](https://cloud.githubusercontent.com/assets/20135113/22275367/4747c854-e27a-11e6-80ac-5b90dd3c8a9e.jpg)
![ayudaangular46](https://cloud.githubusercontent.com/assets/20135113/22275369/474a6b90-e27a-11e6-9077-7649e185a813.jpg)

**Comment by alejo8591** [comment]
@alexospina7 el link del error...!! siempre por favor enviar link del error

**Comment by alexospina7** [comment]
creo que es el mismo http://errors.angularjs.org/1.5.7/$injector/modulerr?p0=initial_spi&p1=Erro…ogleapis.com%2Fajax%2Flibs%2Fangularjs%2F1.5.7%2Fangular.min.js%3A43%3A246

**Comment by alejo8591** [comment]
agregar módulos en el `index.html` con el siguiente orden:
```html
<script type="text/javascript" src="js/controllers.js"></script>
<script type="text/javascript" src="js/app.js"></script>
```

**Comment by alexospina7** [comment]
eso ya lo tenia

**Comment by alejo8591** [comment]
por favor mostrarme el contenido de cada archivo

**Comment by alexospina7** [comment]
![ayudaangular30](https://cloud.githubusercontent.com/assets/20135113/22276598/c9c5b6d0-e282-11e6-903e-9177b24706d9.jpg)

**Comment by alejo8591** [comment]
@alexospina7 de nuevo y al igual que el otro issues por favor seguir indicaciones, hay dos indicaciones que te he dado y no las sigues, hasta que no las sigas no te continuo ayudando:

* [Primera indicación](https://github.com/alejo8591/unipiloto-apm-4/issues/31#issuecomment-274985843)
* [segunda indicación no seguida](https://github.com/alejo8591/unipiloto-apm-4/issues/31#issuecomment-275007897)

**Si no sigues instrucciones de seguro no podré seguir ayudando**

**Comment by alexospina7** [comment]
yo seguí las indicaciones por favor mirar bien

**Comment by alejo8591** [comment]
De nuevo mis ojos me engañan pero las dos indicaciones no las veo reflejadas en la última imagen del `index.html`:

* [Primera indicación](https://github.com/alejo8591/unipiloto-apm-4/issues/31#issuecomment-274985843)
* [segunda indicación no seguida](https://github.com/alejo8591/unipiloto-apm-4/issues/31#issuecomment-275007897)

![captura de pantalla 2017-01-24 a las 10 26 40 p m](https://cloud.githubusercontent.com/assets/1151850/22276802/45e4a1d0-e284-11e6-9913-57d4b7ebefa4.png)

**Comment by alexospina7** [comment]
![ayudaangular47](https://cloud.githubusercontent.com/assets/20135113/22276864/b201e3a0-e284-11e6-9cf1-3a037cc32832.jpg)

**Comment by alexospina7** [comment]
escogí la imagen incorrecta pero ya lo habia hecho y sale el mismo error

**Comment by alejo8591** [comment]
@alexospina7 con todo respeto; pero le cuesta seguir indicaciones mire la [segunda indicación](https://github.com/alejo8591/unipiloto-apm-4/issues/31#issuecomment-275007897):
agregar módulos en el `index.html` con el siguiente orden:

```html
<script type="text/javascript" src="js/controllers.js"></script>
<script type="text/javascript" src="js/app.js"></script>
```

**Comment by alexospina7** [comment]
![ayudaangular48](https://cloud.githubusercontent.com/assets/20135113/22276922/4aeb1212-e285-11e6-8c7c-5514a47cdb2c.jpg)

**Comment by alexospina7** [comment]
cambiar <script type="text/javascript" src="js/controllers.js"></script>
<script type="text/javascript" src="js/app.js"></script> pensaría que no cambia nada, sin embargo sale el mismo error en la herramienta del desarrollador

**Comment by alejo8591** [comment]
@alexospina7 ya revise el ejercicio con respecto a: `https://github.com/alejo8591/unipiloto-apm-4/tree/master/modules/module_3/lab18` y tienes errores de sintaxis...

**Comment by alexospina7** [comment]
pero si yo descarge el repositorio y lo copie en htdocs

**Comment by alexospina7** [comment]
pero si yo descarge el repositorio, lo copie y lo pegue en htdocs

**Comment by alejo8591** [comment]
**Descargado del repo oficial, probado en XAMPP, y por favor mirar la hora y la fecha, no tuve que cambiar nada, tal cual el ejercicio, por favor revisar porque tuve que decirte que cambies algunas cosas de sintaxis y agregar módulos, así que verificar bien...**
![captura de pantalla 2017-01-25 a las 12 54 34 a m](https://cloud.githubusercontent.com/assets/1151850/22279472/0f234a10-e299-11e6-9801-bdd4c39c5bad.png)

![captura de pantalla 2017-01-25 a las 12 58 19 a m](https://cloud.githubusercontent.com/assets/1151850/22279569/79a6c02e-e299-11e6-93e2-5d485920e789.png)

![captura de pantalla 2017-01-25 a las 12 58 35 a m](https://cloud.githubusercontent.com/assets/1151850/22279580/8210827c-e299-11e6-9e4c-7187126a9457.png)

![captura de pantalla 2017-01-25 a las 12 58 51 a m](https://cloud.githubusercontent.com/assets/1151850/22279585/89708878-e299-11e6-97d5-faa617dadcf6.png)

**Comment by alexospina7** [comment]
![ayudaangular49](https://cloud.githubusercontent.com/assets/20135113/22312116/94aa8064-e324-11e6-9981-9b20d2c08ca3.jpg)
