### ISSUE TITLE
Error en SF205-01 al ejectuar en Node.js - cordova run android

### ISSUE THREAD

**Issue by nubia-pulido** [alejo8591/unipiloto-apm-4#9]
![image](https://cloud.githubusercontent.com/assets/20135121/17078099/bed005fc-50ae-11e6-9f5e-de9b5cfbb2d3.png)

Error: Failed to find 'ANDROID_HOME' environment variable. Try setting setting i
t manually.
Failed to find 'android' command in your 'PATH'. Try update your 'PATH' to inclu
de path to valid SDK directory.

**Comment by alejo8591** [comment]
https://github.com/alejo8591/unipiloto-apm-4/issues/13
